View my orders Card
Advanced-computer-lab-2024/Rahhal pull request #131
Opened 2024-11-07 20:29 UTC by AbdallahAhmadd

### Problems in this PR i cant find solution to
- When rating, the rate button changes on refresh not dynamically
- When creating the rating to product (fetch api) I dont fetch user data to get username, i added default nanna

### screenshots

<img width="1440" alt="Screenshot 2024-11-07 at 9 30 17 PM" src="https://github.com/user-attachments/assets/46d1f964-6e6f-4af4-a247-2129960b09d2">
<img width="1440" alt="Screenshot 2024-11-07 at 10 23 53 PM" src="https://github.com/user-attachments/assets/bcf0741f-74b5-4916-b7bd-38ad78354940">
<img width="1440" alt="Screenshot 2024-11-07 at 10 24 15 PM" src="https://github.com/user-attachments/assets/5ad5eed6-a703-4379-9e51-5eb236245af8">

2024-11-07 21:48 UTC, dodzii requested changes
Great work, Abdallah! Left one comment to be discussed.

2024-11-07 22:14 UTC, AhmedHawater2003 requested changes
Great work my friend 🥳❤️

I just left some comments that I think should be resolved 🙏

2024-11-08 17:36 UTC, AhmedHawater2003 approved these changes

2024-11-08 17:39 UTC, merged

2026-09-15 21:05 UTC, sgzerbo commented on client/src/features/home/types/home-page-types.d.ts
>  }
placeholder